---
# OCP cluster
ocp_namespace: jtac-ops

# VM
vm_name: rh-edge-node
vm_memory_mb: 8192
vm_cpus: 4
vm_disk_gb: 40
vm_mac: "52:54:00:ae:11:01"

# Image
image_name: rh-edge-node
image_tag: latest
authfile: "{{ playbook_dir }}/.creds/pull-secret.json"
rhsm_user_file: "{{ playbook_dir }}/.creds/rhsm-user.txt"
rhsm_pass_file: "{{ playbook_dir }}/.creds/rhsm-pass.txt"

# Demo
dashboard_nodeport: 30888

# Skupper — set after cluster setup
skupper_grant_url: ""
skupper_grant_code: ""
skupper_grant_ca: ""
